### ISSUE TITLE
thursday not working on OSX

### ISSUE THREAD

**Issue by kheuton** [mswift42/intellij-ui-themes#1]
The thursday theme completely breaks IntelliJ IDEA 2019.2.1 (Community Edition) on OSX 10.14.6. Ctrl+F stops working, the preferences tab goes completely blank while a project is open, and many other things become unresponsive. I'm not even sure how to begin debugging or where to look for the issue

**Comment by mswift42** [comment]
I'm sorry, but I think you need to report this to Jetbrains. 

I do not have access to a Mac, under Linux there is no problem with the plugin (or any of my ui plugins, which are built using the same template) and no one else has reported a problem.

**Comment by mswift42** [comment]
Did you report this to Jetbrains, or has your issue been solved any other way?

**Comment by kheuton** [comment]
I opened it with jetbrains: https://youtrack.jetbrains.com/issue/IDEA-222500

**Comment by mswift42** [comment]
I'm going to close this now, because the jetbrains issue has been closed as well.
