### ISSUE TITLE
soft-charcoal: alternate table row background

### ISSUE THREAD

**Issue by callumenator** [mswift42/intellij-ui-themes#2]
Thanks for this theme, i really like it. One small issue I have is with the background colour of some elements, like alternating rows in a table:

<img width="1683" alt="Screen Shot 2019-09-21 at 12 49 43 pm" src="https://user-images.githubusercontent.com/1724524/65366999-a4beed00-dc6e-11e9-9d76-b4c8ce4718ca.png">

A similar thing looks like it is happening on the active cell in a jupyter notebook for example. Is the current style there intentional? If not, would it be possible to have something with more contrast by dimming the background?

**Comment by mswift42** [comment]
Thank you for the bug report.

I've changed the Table-striped color to a more readable color.

Please let me know if you are happy (or unhappy) with the change after you have received the update from the Jetbrains marketplace.

**Comment by callumenator** [comment]
That's perfect for the table striping, thanks! The issue with active cell in jupyter notebook is still there fyi (although it doesn't seem to happen for cells in plain scientific mode):

<img width="913" alt="Screen Shot 2019-09-24 at 9 49 45 pm" src="https://user-images.githubusercontent.com/1724524/65509306-84fd2280-df15-11e9-9780-9bca7cd87d3d.png">

But feel free to close this issue, thanks again.

**Comment by callumenator** [comment]
Actually ignore ^ about jupyter, that is controlled in the color scheme.
