### ISSUE TITLE
Text selection issue in silkworm and in white-sand-ui

### ISSUE THREAD

**Issue by num8er** [mswift42/intellij-ui-themes#4]
Need to fix Text selection issue in silkworm and in white-sand-ui. 

Selection becomes invisible when line highlighting at same line with selection.

For now I'm fixing it manually by entering `Preferences->Editor->Color Scheme->General` and changing color for `Editor->Selection background` to `#BBB6AF` (or something grayish).

But needed to have it out of box. 

Current: http://joxi.ru/bmoBBLS3E7Mgry
After edit: http://joxi.net/KAxggxUZBv0J28

**Comment by mswift42** [comment]
Would you be happy with selection color background set to #f9f0e8 ?

**Comment by num8er** [comment]
> f9f0e8

Yes, it's great

screenshot: http://joxi.ru/MAjRRQsjX15VAe

**Comment by num8er** [comment]
I've also added foreground color: #76690B
makes it more "sandy" like "sun shining on selection and golden parts of code is visible" (:
screenshot: http://joxi.ru/Vm6kkLC4EReE2Z

what's Your opinion?

**Comment by mswift42** [comment]
looks good.
I've just committed a fix with commit 254908bb72b0e8a8d5cd0e0cd84104fdc90307c9.

The jetbrains plugin update should be available in the next few days.
I am closing this issue now, if you have any other issues please let me know.
