### ISSUE TITLE
thursday theme: file and diff colors

### ISSUE THREAD

**Issue by JoachimR** [mswift42/intellij-ui-themes#5]
Thank you for this nice light theme!

I wanted to suggest some color changes. 

<img width="394" alt="Screen Shot 2020-07-14 at 7 36 33 AM" src="https://user-images.githubusercontent.com/2596911/87388552-571cc380-c5a5-11ea-88bd-1e22cd8caadc.png">

The test file color is too bright and stands out compared to the rest of the colors

<img width="1039" alt="Screen Shot 2020-07-14 at 7 37 03 AM" src="https://user-images.githubusercontent.com/2596911/87388557-597f1d80-c5a5-11ea-98d3-7b897d73e4ac.png">

The black on purple diff makes it hard to read, especially for bigger diffs 

But those are highly subjective so feel free to close as "wontfix" :)

**Comment by mswift42** [comment]
Thanks, the updated plugin with brighter colors should be available in the next few days.

If you have any other problems / suggestions please feel free to open a new issue.
