### ISSUE TITLE
thursday theme: dark color on dark background

### ISSUE THREAD

**Issue by JoachimR** [mswift42/intellij-ui-themes#6]
Hello,

I have two more suggestions

The quick search (using `shift shift` in IntelliJ) makes it hard to read when the search term is marked in the list:
<img width="676" alt="Screen Shot 2020-07-16 at 8 39 07 AM" src="https://user-images.githubusercontent.com/2596911/87635864-0b525180-c740-11ea-80ed-64ac95a0a376.png">

The selected file in the project view is also a little bit hard to read due to the dark-ish background color 
<img width="321" alt="Screen Shot 2020-07-16 at 8 39 18 AM" src="https://user-images.githubusercontent.com/2596911/87635874-0e4d4200-c740-11ea-85a2-d626b1dfcf4e.png">

It is not urgent so you might want to wait with another update to not annoy users too much with updates :)

also just again my opinion so feel free to ignore

thanks

**Comment by mswift42** [comment]
Hi, this has been fixed with version 0.1.6, which should be available in the next two days.

Thanks for the bug report and keep em coming.

martin
